/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ContextBox: typeof import('./src/components/common/ContextBox.vue')['default']
    copy: typeof import('./src/components/page/Board/Notice/NoticeSearch copy.vue')['default']
    FNoticeMain: typeof import('./src/components/page/Board/Notice/FNoticeMain.vue')['default']
    FNoticeMain2: typeof import('./src/components/page/Board/Notice/FNoticeMain2.vue')['default']
    FNoticeModal: typeof import('./src/components/page/Board/Notice/FNoticeModal.vue')['default']
    FNoticeModal2: typeof import('./src/components/page/Board/Notice/FNoticeModal2.vue')['default']
    FNoticeSearch: typeof import('./src/components/page/Board/Notice/FNoticeSearch.vue')['default']
    FNoticeSearch2: typeof import('./src/components/page/Board/Notice/FNoticeSearch2.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LeftManuBar: typeof import('./src/components/layout/LeftManuBar.vue')['default']
    LoginMain: typeof import('./src/components/page/Login/LoginMain.vue')['default']
    NoticeDetail: typeof import('./src/components/page/Board/Notice/NoticeDetail.vue')['default']
    NoticeMain: typeof import('./src/components/page/Board/Notice/NoticeMain.vue')['default']
    NoticeMain2: typeof import('./src/components/page/Board/Notice/NoticeMain2.vue')['default']
    NoticeModal: typeof import('./src/components/page/Board/Notice/NoticeModal.vue')['default']
    NoticeModal2: typeof import('./src/components/page/Board/Notice/NoticeModal2.vue')['default']
    NoticeSearch: typeof import('./src/components/page/Board/Notice/NoticeSearch.vue')['default']
    NoticeSearch2: typeof import('./src/components/page/Board/Notice/NoticeSearch2.vue')['default']
    Pagination: typeof import('./src/components/common/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
